// @ts-check
const env = process.env.ENV || "localhost";

const url =
    env === "codespace"
        ? "https://hgodinho-refactored-space-garbanzo-q4qq76v9rvc9px7-3000.preview.app.github.dev"
        : env === "production"
        ? "https://hgodinho.github.io"
        : "http://localhost:3000";

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
    sidebar: [
        "doc",
        "tables/tables",
        // 'concepts/pre_defined',
        {
            type: "doc",
            label: "Glossário",
            id: "glossario/glossario",
        },
        "todo/to-do",
        {
            type: "link",
            label: "MDORIM",
            href: `/elucidario/mdorim`,
        },
        {
            type: "link",
            label: "pub-gen",
            href: `/elucidario/pub-gen`,
        },
    ],
};

module.exports = sidebars;
