// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
    sidebar: [
        'doc',
        'tables/tables',
        {
            type: 'category',
            label: 'Entidades',
            items: [
                'entities/entities',
                'entities/generic',
                'entities/concept',
                'entities/user',
                'entities/agent',
                'entities/object',
                'entities/set',
                'entities/place',
                'entities/event',
                'entities/textual-object',
                'entities/visual-object',
                'entities/digital-object',
            ],
        },
        'metadata/metadata',
        'concepts/pre_defined',
        {
            type: 'doc',
            label: 'Glossário',
            id: 'glossario/glossario'
        }
    ]
};

module.exports = sidebars;
